### ISSUE TITLE
fail to build on my old freebsd 11.2 system

### ISSUE THREAD

**Issue by techman-001** [Crest/swdcom#2]
tp@gronk:~/downloads/swdcom-master% make
cc -O2 -pipe -std=c99 -Weverything -I/usr/local/include -I/usr/local/include/stlink -L/usr/local/lib -o swd2 swd2.c  -lstlink
swd2.c:86:25: error: use of undeclared identifier 'STLINK_SERIAL_MAX_SIZE'
open_or_die(char serial[STLINK_SERIAL_MAX_SIZE])

11.2-RELEASE-p9 GENERIC  amd64
stlink-1.5.0_2   STM32 ST-Link JTAG variant tools

**Comment by Crest** [comment]
The latest version of swdcom (as 2020-08-22) of requires stlink 1.6.x.
